// Tipos posibles para columnas:
//   'dni'   → INTEGER UNIQUE NOT NULL  (campo especial)
//   'text'  → TEXT
//   'date'  → DATE
//   'int'   → INTEGER
//   'money' → NUMERIC(12,2)
//
// Columnas id, created_at, updated_at se añaden automáticamente en el SQL generado.

const CAS_COLS = [
  { key: 'dni', label: 'DNI', type: 'dni' },
  { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
  { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
  { key: 'faltas', label: 'Faltas', type: 'int' },
  { key: 'cargo', label: 'Cargo', type: 'text' },
  { key: 'snp', label: 'S.N.P.', type: 'text' },
  { key: 'r_basica', label: 'R. Básica', type: 'money' },
  { key: 'r_reunif', label: 'R. Reunif.', type: 'money' },
  { key: 'retrib_contr', label: 'Retrib. Contr.', type: 'money' },
  { key: 'inc_10_23', label: 'Inc. 10/23', type: 'money' },
  { key: 'inc_3', label: 'Inc. 3%', type: 'money' },
  { key: 'ds311_2022_ef', label: 'DS311-2022-EF', type: 'money' },
  { key: 'ds313_2023_ef', label: 'DS313-2023-EF', type: 'money' },
  { key: 'ds265_2024ef', label: 'DS265-2024-EF', type: 'money' },
  { key: 'ds279_2024ef', label: 'DS279-2024-EF', type: 'money' },
  { key: 'ds327_2025ef', label: 'DS327-2025-EF', type: 'money' },
  { key: 'ref', label: 'Ref.', type: 'money' },
  { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
  { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
  { key: 'f_pens', label: 'F. Pens.', type: 'money' },
  { key: 'p_seg', label: 'P. Seg.', type: 'money' },
  { key: 'c_var', label: 'C. Var.', type: 'money' },
  { key: 'coop_la_rehab', label: 'Coop. La Rehab.', type: 'money' },
  { key: 'dscto_fesalud', label: 'Dscto. FeSalud', type: 'money' },
  { key: 'rimac_seg', label: 'Rimac Seg.', type: 'money' },
  { key: 'mas_vida', label: 'Más Vida', type: 'money' },
  { key: 'la_positiva_seguros', label: 'La Positiva Seguros', type: 'money' },
  { key: 'r_jud', label: 'R. Jud.', type: 'money' },
  { key: 'coop_san_ch', label: 'Coop. San Ch.', type: 'money' },
  { key: 'ret_4ta_categ', label: 'Ret. 4ta Categ.', type: 'money' },
  { key: 'cop_nieves', label: 'Cop. Nieves', type: 'money' },
  { key: 'san_miguel', label: 'San Miguel', type: 'money' },
  { key: 'coop_sta_mm', label: 'Coop. Sta. MM', type: 'money' },
  { key: 'c_sind', label: 'C. Sind.', type: 'money' },
  { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
  { key: 't_liquido', label: 'Total Líquido', type: 'money' },
  { key: 'firma', label: 'Firma', type: 'text' },
  { key: 'observaciones', label: 'Observaciones', type: 'text' },
]

const EMPL_PI_COLS = [
  { key: 'dni', label: 'DNI', type: 'dni' },
  { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
  { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
  { key: 'cargo', label: 'Cargo', type: 'text' },
  { key: 'snp', label: 'S.N.P.', type: 'text' },
  { key: 'rem_cont', label: 'Rem. Cont.', type: 'money' },
  { key: 'neg_cent_2024', label: 'Neg. Cent. 2024', type: 'money' },
  { key: 'otros_r', label: 'Otros R.', type: 'money' },
  { key: 'inc_neg_col_ds314_23', label: 'Inc. DS314-23', type: 'money' },
  { key: 'inc_neg_col_ds268_24', label: 'Inc. DS268-24', type: 'money' },
  { key: 'inc_neg_col_ds280_24', label: 'Inc. DS280-24', type: 'money' },
  { key: 'inc_neg_col_ds326_25', label: 'Inc. DS326-25', type: 'money' },
  { key: 'reintegro', label: 'Reintegro', type: 'money' },
  { key: 'ref', label: 'Ref.', type: 'money' },
  { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
  { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
  { key: 'f_pens', label: 'F. Pens.', type: 'money' },
  { key: 'p_seg', label: 'P. Seg.', type: 'money' },
  { key: 'c_var', label: 'C. Var.', type: 'money' },
  { key: 'ir_5ta_cat', label: 'IR 5ta Cat.', type: 'money' },
  { key: 'mas_vida', label: 'Más Vida', type: 'money' },
  { key: 'seg_rimac', label: 'Seg. Rimac', type: 'money' },
  { key: 'interseguro', label: 'Interseguro', type: 'money' },
  { key: 'coop_s_crist', label: 'Coop. S. Crist.', type: 'money' },
  { key: 'faltas', label: 'Faltas', type: 'int' },
  { key: 'ret_jud', label: 'Ret. Jud.', type: 'money' },
  { key: 'coop_san_miguel', label: 'Coop. San Miguel', type: 'money' },
  { key: 'coop_m_magd', label: 'Coop. M. Magd.', type: 'money' },
  { key: 'desc_var', label: 'Desc. Var.', type: 'money' },
  { key: 'seguro_fe_salud', label: 'Seguro Fe Salud', type: 'money' },
  { key: 'banco_pichincha', label: 'Banco Pichincha', type: 'money' },
  { key: 'fe_salud', label: 'Fe Salud', type: 'money' },
  { key: 'coop_la_rehabilitadora', label: 'Coop. La Rehabilitadora', type: 'money' },
  { key: 'coop_virgen_las_nieves', label: 'Coop. Virgen Las Nieves', type: 'money' },
  { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
  { key: 't_liquido', label: 'Total Líquido', type: 'money' },
  { key: 'observaciones', label: 'Observaciones', type: 'text' },
]

export const PLANILLAS = [
  {
    slug: 'obreros-permanentes',
    tabla: 'obreros_permanentes',
    label: 'Obreros Permanentes',
    grupo: 'Obreros',
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'f_ingreso', label: 'F. Ingreso', type: 'date' },
      { key: 'dias_lab', label: 'Días Lab.', type: 'int' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 'rem_bas', label: 'Rem. Bas.', type: 'money' },
      { key: 'rem', label: 'Rem.', type: 'money' },
      { key: 'cv_historial', label: 'CV Historial', type: 'money' },
      { key: 'b_famil', label: 'B. Famil.', type: 'money' },
      { key: 'p_pacto', label: 'P. Pacto', type: 'money' },
      { key: 'mov_p2014', label: 'Mov. P2014', type: 'money' },
      { key: 'pacto_2013', label: 'Pacto 2013', type: 'money' },
      { key: 'pacto_2014', label: 'Pacto 2014', type: 'money' },
      { key: 'laudo_2019', label: 'Laudo 2019', type: 'money' },
      { key: 'inc_3_3', label: 'Inc. 3.3%', type: 'money' },
      { key: 'inc_10_23', label: 'Inc. 10/23', type: 'money' },
      { key: 'inc_3', label: 'Inc. 3%', type: 'money' },
      { key: 'otros', label: 'Otros', type: 'money' },
      { key: 'riesgo_salud', label: 'Riesgo Salud', type: 'money' },
      { key: 'neg_col_ds311_22', label: 'Neg. Col. DS311-22', type: 'money' },
      { key: 'neg_col_ds265_24', label: 'Neg. Col. DS265-24', type: 'money' },
      { key: 'neg_col_ds279_24', label: 'Neg. Col. DS279-24', type: 'money' },
      { key: 'neg_col_ds325_25', label: 'Neg. Col. DS325-25', type: 'money' },
      { key: 'otros_r', label: 'Otros R.', type: 'money' },
      { key: 'ref_mov_laudo_2019', label: 'Ref. Mov. Laudo 2019', type: 'money' },
      { key: 'ref_pacto_2014', label: 'Ref. Pacto 2014', type: 'money' },
      { key: 'asig_fam_10rmv', label: 'Asig. Fam. 10RMV', type: 'money' },
      { key: 'ref_mov_histor', label: 'Ref. Mov. Histor.', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
      { key: 'reunif', label: 'Reunif.', type: 'money' },
      { key: 'fdo_pens', label: 'Fdo. Pens.', type: 'money' },
      { key: 'p_seg', label: 'P. Seg.', type: 'money' },
      { key: 'positiva_vida', label: 'Positiva Vida', type: 'money' },
      { key: 'c_var', label: 'C. Var.', type: 'money' },
      { key: 'rimac_seg', label: 'Rimac Seg.', type: 'money' },
      { key: 'coop_san_ch', label: 'Coop. San Ch.', type: 'money' },
      { key: 'coop_san_miguel', label: 'Coop. San Miguel', type: 'money' },
      { key: 'coop_rehabilita', label: 'Coop. Rehabilita', type: 'money' },
      { key: 'dscto_autoriz_ii', label: 'Dscto. Autoriz. II', type: 'money' },
      { key: 'faltas', label: 'Faltas', type: 'int' },
      { key: 'ret_jud', label: 'Ret. Jud.', type: 'money' },
      { key: 'pichincha', label: 'Pichincha', type: 'money' },
      { key: 'mas_vida', label: 'Más Vida', type: 'money' },
      { key: 'fesalud', label: 'FeSalud', type: 'money' },
      { key: 'dscto_somun', label: 'Dscto. SOMUN', type: 'money' },
      { key: 'coop_virgen_n', label: 'Coop. Virgen N.', type: 'money' },
      { key: 'coop_sta_mm', label: 'Coop. Sta. MM', type: 'money' },
      { key: 'rta_5ta_cat', label: 'Rta. 5ta Cat.', type: 'money' },
      { key: 'c_sindical', label: 'C. Sindical', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'obreros-plazo-indeterminado',
    tabla: 'obreros_plazo_indeterminado',
    label: 'Obreros Plazo Indeterminado',
    grupo: 'Obreros',
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
      { key: 'dias_lab', label: 'Días Lab.', type: 'int' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 'r_basica', label: 'R. Básica', type: 'money' },
      { key: 'r_reunif', label: 'R. Reunif.', type: 'money' },
      { key: 'mov_p2014', label: 'Mov. P2014', type: 'money' },
      { key: 'p_pacto', label: 'P. Pacto', type: 'money' },
      { key: 'inc_anc10_m038_11_rh', label: 'Inc. Anc10 M038-11 RH', type: 'money' },
      { key: 'rem_cont_plazo_indet', label: 'Rem. Cont. Plazo Indet.', type: 'money' },
      { key: 'pacto_2013', label: 'Pacto 2013', type: 'money' },
      { key: 'pacto_2014', label: 'Pacto 2014', type: 'money' },
      { key: 'laudo_2019', label: 'Laudo 2019', type: 'money' },
      { key: 'inc_rmv_ds016_05', label: 'Inc. RMV DS016-05', type: 'money' },
      { key: 'inc_rmv_ds022_07', label: 'Inc. RMV DS022-07', type: 'money' },
      { key: 'inc_anc_mem005_09', label: 'Inc. Anc Mem005-09', type: 'money' },
      { key: 'niv_fe_errat_rga002_16', label: 'Niv. Fe Errat. RGA002-16', type: 'money' },
      { key: 'ref_pacto_2014', label: 'Ref. Pacto 2014', type: 'money' },
      { key: 'ref_mov_laudo_2019', label: 'Ref. Mov. Laudo 2019', type: 'money' },
      { key: 'asig_fam_10rmv', label: 'Asig. Fam. 10RMV', type: 'money' },
      { key: 'conv_col_ds325_25', label: 'Conv. Col. DS325-25', type: 'money' },
      { key: 'conv_col_ds265_24', label: 'Conv. Col. DS265-24', type: 'money' },
      { key: 'conv_col_ds279_24', label: 'Conv. Col. DS279-24', type: 'money' },
      { key: 'neg_col_ds313_23', label: 'Neg. Col. DS313-23', type: 'money' },
      { key: 'conv_col_ds311_22', label: 'Conv. Col. DS311-22', type: 'money' },
      { key: 'riesgo_salud', label: 'Riesgo Salud', type: 'money' },
      { key: 'ref_mov_98_ra005_22', label: 'Ref. Mov. 98 RA005-22', type: 'money' },
      { key: 'otros_r', label: 'Otros R.', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
      { key: 'f_pens', label: 'F. Pens.', type: 'money' },
      { key: 'p_seg', label: 'P. Seg.', type: 'money' },
      { key: 'c_var', label: 'C. Var.', type: 'money' },
      { key: 'mas_vida', label: 'Más Vida', type: 'money' },
      { key: 'positiva_vida', label: 'Positiva Vida', type: 'money' },
      { key: 'rimac_seg', label: 'Rimac Seg.', type: 'money' },
      { key: 'pichincha', label: 'Pichincha', type: 'money' },
      { key: 'coop_san_miguel', label: 'Coop. San Miguel', type: 'money' },
      { key: 'coop_rehabilita', label: 'Coop. Rehabilita', type: 'money' },
      { key: 'renta_5ta_cat', label: 'Renta 5ta Cat.', type: 'money' },
      { key: 'faltas', label: 'Faltas', type: 'int' },
      { key: 'r_jud', label: 'R. Jud.', type: 'money' },
      { key: 'interseguro', label: 'Interseguro', type: 'money' },
      { key: 'somun', label: 'SOMUN', type: 'money' },
      { key: 'coop_virgen_n', label: 'Coop. Virgen N.', type: 'money' },
      { key: 'coop_sta_mm', label: 'Coop. Sta. MM', type: 'money' },
      { key: 'fesalud', label: 'FeSalud', type: 'money' },
      { key: 'coop_san_ch', label: 'Coop. San Ch.', type: 'money' },
      { key: 'c_sind', label: 'C. Sind.', type: 'money' },
      { key: 'dscto_autoriz', label: 'Dscto. Autoriz.', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'obreros-mandato-judicial',
    tabla: 'obreros_mandato_judicial',
    label: 'Obreros Mandato Judicial',
    grupo: 'Obreros',
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
      { key: 'dias_lab', label: 'Días Lab.', type: 'int' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 'rem_cont_plazo_indet', label: 'Rem. Cont. Plazo Indet.', type: 'money' },
      { key: 'neg_col_ds313_23', label: 'Neg. Col. DS313-23', type: 'money' },
      { key: 'riesgo_salud', label: 'Riesgo Salud', type: 'money' },
      { key: 'asig_fam_10rmv', label: 'Asig. Fam. 10RMV', type: 'money' },
      { key: 'conv_col_ds265_24', label: 'Conv. Col. DS265-24', type: 'money' },
      { key: 'conv_col_ds279_24', label: 'Conv. Col. DS279-24', type: 'money' },
      { key: 'otros_r', label: 'Otros R.', type: 'money' },
      { key: 'conv_col_ds325_25', label: 'Conv. Col. DS325-25', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
      { key: 'f_pens', label: 'F. Pens.', type: 'money' },
      { key: 'p_seg', label: 'P. Seg.', type: 'money' },
      { key: 'c_var', label: 'C. Var.', type: 'money' },
      { key: 'mas_vida', label: 'Más Vida', type: 'money' },
      { key: 'rimac_seg', label: 'Rimac Seg.', type: 'money' },
      { key: 'coop_san_miguel', label: 'Coop. San Miguel', type: 'money' },
      { key: 'coop_rehabilita', label: 'Coop. Rehabilita', type: 'money' },
      { key: 'renta_5ta_cat', label: 'Renta 5ta Cat.', type: 'money' },
      { key: 'faltas', label: 'Faltas', type: 'int' },
      { key: 'r_jud', label: 'R. Jud.', type: 'money' },
      { key: 'pichincha', label: 'Pichincha', type: 'money' },
      { key: 'somun', label: 'SOMUN', type: 'money' },
      { key: 'coop_sta_mm', label: 'Coop. Sta. MM', type: 'money' },
      { key: 'fesalud', label: 'FeSalud', type: 'money' },
      { key: 'coop_san_ch', label: 'Coop. San Ch.', type: 'money' },
      { key: 'c_sind', label: 'C. Sind.', type: 'money' },
      { key: 'dscto_ii', label: 'Dscto. II', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'obreros-concurso',
    tabla: 'obreros_concurso',
    label: 'Obreros Concurso',
    grupo: 'Obreros',
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
      { key: 'dias_lab', label: 'Días Lab.', type: 'int' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 'r_basica', label: 'R. Básica', type: 'money' },
      { key: 'rem_reunificada', label: 'Rem. Reunificada', type: 'money' },
      { key: 'rem_cont_plazo_indet', label: 'Rem. Cont. Plazo Indet.', type: 'money' },
      { key: 'ref_mov_ra1596_98_ampi', label: 'Ref. Mov. RA1596-98 AMPI', type: 'money' },
      { key: 'bonif_riesgo_salud_10', label: 'Bonif. Riesgo Salud 10%', type: 'money' },
      { key: 'otros_personal_servicio', label: 'Otros Personal Servicio', type: 'money' },
      { key: 'subv_financ_laudo_2014', label: 'Subv. Financ. Laudo 2014', type: 'money' },
      { key: 'ds311_2022_ef', label: 'DS311-2022-EF', type: 'money' },
      { key: 'ds313_23_ef', label: 'DS313-23-EF', type: 'money' },
      { key: 'ds265_24_ef', label: 'DS265-24-EF', type: 'money' },
      { key: 'asig_fam', label: 'Asig. Fam.', type: 'money' },
      { key: 'neg_col_ctral_2024_2025', label: 'Neg. Col. Ctral. 2024-2025', type: 'money' },
      { key: 'neg_col_ctral_2025_2026', label: 'Neg. Col. Ctral. 2025-2026', type: 'money' },
      { key: 'otros_r', label: 'Otros R.', type: 'money' },
      { key: 'costo_vida_laudo_2019', label: 'Costo Vida Laudo 2019', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
      { key: 'f_pens', label: 'F. Pens.', type: 'money' },
      { key: 'p_seg', label: 'P. Seg.', type: 'money' },
      { key: 'c_var', label: 'C. Var.', type: 'money' },
      { key: 'comis_variable', label: 'Comis. Variable', type: 'money' },
      { key: 'inasistencias', label: 'Inasistencias', type: 'int' },
      { key: 'retenc_judicial', label: 'Retenc. Judicial', type: 'money' },
      { key: 'rimac', label: 'Rimac', type: 'money' },
      { key: 'cuota_sindical', label: 'Cuota Sindical', type: 'money' },
      { key: 'coop_la_rehabilitadora', label: 'Coop. La Rehabilitadora', type: 'money' },
      { key: 'coop_san_miguel', label: 'Coop. San Miguel', type: 'money' },
      { key: 'coop_san_cristobal', label: 'Coop. San Cristóbal', type: 'money' },
      { key: 'coop_virgen_las_nieves', label: 'Coop. Virgen Las Nieves', type: 'money' },
      { key: 'otros_r_dtos', label: 'Otros R. Dtos.', type: 'money' },
      { key: 'dscto_ii', label: 'Dscto. II', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'obreros-necesidad-mercado',
    tabla: 'obreros_necesidad_mercado',
    label: 'Obreros Necesidad de Mercado',
    grupo: 'Obreros',
    sinAutoTotales: true, // sin componentes detallados; totales son manuales
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
      { key: 'dias_lab', label: 'Días Lab.', type: 'int' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'empleados-permanentes',
    tabla: 'empleados_permanentes',
    label: 'Empleados Permanentes',
    grupo: 'Empleados',
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
      { key: 'cargo', label: 'Cargo', type: 'text' },
      { key: 'vacaciones', label: 'Vacaciones', type: 'money' },
      { key: 'niv_rem', label: 'Niv. Rem.', type: 'text' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 'r_basica', label: 'R. Básica', type: 'money' },
      { key: 'r_reunif', label: 'R. Reunif.', type: 'money' },
      { key: 'b_familiar', label: 'B. Familiar', type: 'money' },
      { key: 'b_pers', label: 'B. Pers.', type: 'money' },
      { key: 'inc_neg_col_ds320_22', label: 'Inc. DS320-22', type: 'money' },
      { key: 'memo_159_2025_ogrrhh_mpi', label: 'Memo 159-2025 OGRRHH-MPI', type: 'money' },
      { key: 'c_vida_tph', label: 'C. Vida TPH', type: 'money' },
      { key: 'reaj_c_vida_10', label: 'Reaj. C. Vida 10%', type: 'money' },
      { key: 'reaj_c_vida_7', label: 'Reaj. C. Vida 7%', type: 'money' },
      { key: 'inc_neg_col_ds314_23', label: 'Inc. DS314-23', type: 'money' },
      { key: 'inc_neg_col_ds268_24', label: 'Inc. DS268-24', type: 'money' },
      { key: 'inc_neg_col_ds280_24', label: 'Inc. DS280-24', type: 'money' },
      { key: 'm_jud_inc_ref_mov', label: 'M. Jud. Inc. Ref. Mov.', type: 'money' },
      { key: 'inc_neg_col_ds326_25', label: 'Inc. DS326-25', type: 'money' },
      { key: 'inc_3_3', label: 'Inc. 3.3%', type: 'money' },
      { key: 'inc_10_23', label: 'Inc. 10/23', type: 'money' },
      { key: 'inc_3', label: 'Inc. 3%', type: 'money' },
      { key: 'bonif_dif', label: 'Bonif. Dif.', type: 'money' },
      { key: 'reinteg', label: 'Reinteg.', type: 'money' },
      { key: 'ref_mov', label: 'Ref. Mov.', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
      { key: 'fdo_pens', label: 'Fdo. Pens.', type: 'money' },
      { key: 'p_seg', label: 'P. Seg.', type: 'money' },
      { key: 'c_var', label: 'C. Var.', type: 'money' },
      { key: 'ir_5ta_cat', label: 'IR 5ta Cat.', type: 'money' },
      { key: 'mas_vida', label: 'Más Vida', type: 'money' },
      { key: 'seg_rimac', label: 'Seg. Rimac', type: 'money' },
      { key: 'interseguro', label: 'Interseguro', type: 'money' },
      { key: 'coop_la_rehabilitad', label: 'Coop. La Rehabilitad.', type: 'money' },
      { key: 'bco_pichincha', label: 'Bco. Pichincha', type: 'money' },
      { key: 'coop_s_cristobal', label: 'Coop. S. Cristóbal', type: 'money' },
      { key: 'ccp', label: 'CCP', type: 'money' },
      { key: 'faltas', label: 'Faltas', type: 'int' },
      { key: 'ret_jud', label: 'Ret. Jud.', type: 'money' },
      { key: 'fe_salud', label: 'Fe Salud', type: 'money' },
      { key: 'dsct_autorizado', label: 'Dsct. Autorizado', type: 'money' },
      { key: 'coop_maria_magdalena', label: 'Coop. María Magdalena', type: 'money' },
      { key: 'la_positiva_vida', label: 'La Positiva Vida', type: 'money' },
      { key: 'coop_san_miguel', label: 'Coop. San Miguel', type: 'money' },
      { key: 'cuota_sindical', label: 'Cuota Sindical', type: 'money' },
      { key: 'coop_virgen_nieves', label: 'Coop. Virgen Nieves', type: 'money' },
      { key: 'descuento_sitramun', label: 'Descuento SITRAMUN', type: 'money' },
      { key: 'regularizacion', label: 'Regularización', type: 'money' },
      { key: 'clap', label: 'CLAP', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'empleados-contrato-plazo-indet',
    tabla: 'empleados_contrato_plazo_indet',
    label: 'Empleados Contrato Plazo Indeterminado',
    grupo: 'Empleados',
    columnas: EMPL_PI_COLS,
  },
  {
    slug: 'empleados-contrato-provisional',
    tabla: 'empleados_contrato_provisional',
    label: 'Empleados Contrato Provisional',
    grupo: 'Empleados',
    columnas: EMPL_PI_COLS,
  },
  {
    slug: 'empleados-mandato-judicial',
    tabla: 'empleados_mandato_judicial_24041',
    label: 'Empleados Mandato Judicial (24041)',
    grupo: 'Empleados',
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
      { key: 'cargo', label: 'Cargo', type: 'text' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 'rem_cont', label: 'Rem. Cont.', type: 'money' },
      { key: 'inc_neg_col_ds314_23', label: 'Inc. DS314-23', type: 'money' },
      { key: 'inc_neg_col_ds268_24', label: 'Inc. DS268-24', type: 'money' },
      { key: 'inc_neg_col_ds280_24', label: 'Inc. DS280-24', type: 'money' },
      { key: 'inc_neg_col_ds326_25', label: 'Inc. DS326-25', type: 'money' },
      { key: 'reintegro', label: 'Reintegro', type: 'money' },
      { key: 'ref', label: 'Ref.', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
      { key: 'f_pens', label: 'F. Pens.', type: 'money' },
      { key: 'p_seg', label: 'P. Seg.', type: 'money' },
      { key: 'c_var', label: 'C. Var.', type: 'money' },
      { key: 'ir_5ta_cat', label: 'IR 5ta Cat.', type: 'money' },
      { key: 'mas_vida', label: 'Más Vida', type: 'money' },
      { key: 'seg_rimac', label: 'Seg. Rimac', type: 'money' },
      { key: 'interseguro', label: 'Interseguro', type: 'money' },
      { key: 'coop_s_crist', label: 'Coop. S. Crist.', type: 'money' },
      { key: 'faltas', label: 'Faltas', type: 'int' },
      { key: 'ret_jud', label: 'Ret. Jud.', type: 'money' },
      { key: 'coop_san_miguel', label: 'Coop. San Miguel', type: 'money' },
      { key: 'coop_m_magd', label: 'Coop. M. Magd.', type: 'money' },
      { key: 'desc_var', label: 'Desc. Var.', type: 'money' },
      { key: 'seguro_fe_salud', label: 'Seguro Fe Salud', type: 'money' },
      { key: 'banco_pichincha', label: 'Banco Pichincha', type: 'money' },
      { key: 'fe_salud', label: 'Fe Salud', type: 'money' },
      { key: 'coop_la_rehabilitadora', label: 'Coop. La Rehabilitadora', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'cas-general',
    tabla: 'cas_general',
    label: 'CAS General',
    grupo: 'CAS',
    columnas: CAS_COLS,
  },
  {
    slug: 'cas-choferes',
    tabla: 'cas_choferes',
    label: 'CAS Choferes',
    grupo: 'CAS',
    columnas: CAS_COLS,
  },
  {
    slug: 'cas-i-2025',
    tabla: 'cas_i_2025',
    label: 'CAS I 2025',
    grupo: 'CAS',
    columnas: CAS_COLS,
  },
  {
    slug: 'cas-ii-2023',
    tabla: 'cas_ii_2023',
    label: 'CAS II 2023',
    grupo: 'CAS',
    columnas: CAS_COLS,
  },
  {
    slug: 'cas-ii-2024',
    tabla: 'cas_ii_2024',
    label: 'CAS II 2024',
    grupo: 'CAS',
    columnas: CAS_COLS,
  },
  {
    slug: 'cas-iii-2025',
    tabla: 'cas_iii_2025',
    label: 'CAS III 2025',
    grupo: 'CAS',
    columnas: CAS_COLS,
  },
  {
    slug: 'cas-funcional',
    tabla: 'cas_funcional',
    label: 'CAS Funcional',
    grupo: 'CAS',
    columnas: CAS_COLS,
  },
  {
    slug: 'cesantes-pensionistas',
    tabla: 'cesantes_pensionistas',
    label: 'Cesantes y Pensionistas',
    grupo: 'Pensionistas',
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'nivel', label: 'Nivel', type: 'text' },
      { key: 'rem_bas', label: 'Rem. Bas.', type: 'money' },
      { key: 'rem_r', label: 'Rem. R.', type: 'money' },
      { key: 'pens_viudez_rmv', label: 'Pens. Viudez RMV', type: 'money' },
      { key: 'art18_dl20530', label: 'Art. 18 DL20530', type: 'money' },
      { key: 'bonif_pers', label: 'Bonif. Pers.', type: 'money' },
      { key: 'ds_276', label: 'DS-276', type: 'money' },
      { key: 'costo_v_acumul_p_viud_ra', label: 'Costo V. Acumul. P. Viud. RA', type: 'money' },
      { key: 'bonif_fam', label: 'Bonif. Fam.', type: 'money' },
      { key: 'ds16_06_1_74', label: 'DS16-06-1-74', type: 'money' },
      { key: 'acumulado_ds039_07_al_ds011_18', label: 'Acum. DS039-07 al DS011-18', type: 'money' },
      { key: 'ds_009_19', label: 'DS-009-19', type: 'money' },
      { key: 'ds_006_20', label: 'DS-006-20', type: 'money' },
      { key: 'ds_006_21', label: 'DS-006-21', type: 'money' },
      { key: 'ds_014_22', label: 'DS-014-22', type: 'money' },
      { key: 'ds_007_23', label: 'DS-007-23', type: 'money' },
      { key: 'ds_002_24', label: 'DS-002-24', type: 'money' },
      { key: 'ds_003_25', label: 'DS-003-25', type: 'money' },
      { key: 'reintegro_rem', label: 'Reintegro Rem.', type: 'money' },
      { key: 'ds_009_2026_ef', label: 'DS-009-2026-EF', type: 'money' },
      { key: 'ref_mov', label: 'Ref. Mov.', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'ss', label: 'SS', type: 'money' },
      { key: 'otros', label: 'Otros', type: 'money' },
      { key: 'ret_jud', label: 'Ret. Jud.', type: 'money' },
      { key: 'coop_san_miguel', label: 'Coop. San Miguel', type: 'money' },
      { key: 'coop_ac_sta_mm', label: 'Coop. AC Sta. MM', type: 'money' },
      { key: 'coop_ac_san_ch', label: 'Coop. AC San Ch.', type: 'money' },
      { key: 'dscto_aut_ascejumi', label: 'Dscto. Aut. ASCEJUMI', type: 'money' },
      { key: 'ascejumi', label: 'ASCEJUMI', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'firma', label: 'Firma', type: 'text' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'gerente-municipal',
    tabla: 'gerente_municipal',
    label: 'Gerente Municipal',
    grupo: 'Autoridades',
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
      { key: 'cargo', label: 'Cargo', type: 'text' },
      { key: 'faltas', label: 'Faltas', type: 'int' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 'ds_413_19_ef', label: 'DS-413-19-EF', type: 'money' },
      { key: 'otros_r', label: 'Otros R.', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
      { key: 'fdo_pens', label: 'Fdo. Pens.', type: 'money' },
      { key: 'p_seg', label: 'P. Seg.', type: 'money' },
      { key: 'c_var', label: 'C. Var.', type: 'money' },
      { key: 'ir_5ta_cat', label: 'IR 5ta Cat.', type: 'money' },
      { key: 'mas_vida', label: 'Más Vida', type: 'money' },
      { key: 'seg_rimac', label: 'Seg. Rimac', type: 'money' },
      { key: 'interseguro', label: 'Interseguro', type: 'money' },
      { key: 'd_aut_sit_mpi', label: 'D. Aut. SIT-MPI', type: 'money' },
      { key: 'dscto_otros', label: 'Dscto. Otros', type: 'money' },
      { key: 'coop_s_crist', label: 'Coop. S. Crist.', type: 'money' },
      { key: 'ccp', label: 'CCP', type: 'money' },
      { key: 'ret_jud', label: 'Ret. Jud.', type: 'money' },
      { key: 'dscto_aut_varios', label: 'Dscto. Aut. Varios', type: 'money' },
      { key: 'coop_m_magd', label: 'Coop. M. Magd.', type: 'money' },
      { key: 'la_positiva_vida', label: 'La Positiva Vida', type: 'money' },
      { key: 'cep', label: 'CEP', type: 'money' },
      { key: 'c_sind_sit_mpi', label: 'C. Sind. SIT-MPI', type: 'money' },
      { key: 'clap', label: 'CLAP', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'firma', label: 'Firma', type: 'text' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    slug: 'alcalde',
    tabla: 'alcalde',
    label: 'Alcalde',
    grupo: 'Autoridades',
    excluirCalculo: ['base'], // 'base' no es descuento; excluir del auto-cálculo
    columnas: [
      { key: 'dni', label: 'DNI', type: 'dni' },
      { key: 'apellidos_y_nombres', label: 'Apellidos y Nombres', type: 'text', required: true },
      { key: 'cargo', label: 'Cargo', type: 'text' },
      { key: 'fecha_ing', label: 'Fecha de Ingreso', type: 'date' },
      { key: 'faltas', label: 'Faltas', type: 'int' },
      { key: 'niv_rem', label: 'Niv. Rem.', type: 'text' },
      { key: 'snp', label: 'S.N.P.', type: 'text' },
      { key: 'ds_413_19_ef', label: 'DS-413-19-EF', type: 'money' },
      { key: 'otros_r', label: 'Otros R.', type: 'money' },
      { key: 'inc_neg_col_ds314_23', label: 'Inc. DS314-23', type: 'money' },
      { key: 'inc_neg_col_ds268_24', label: 'Inc. DS268-24', type: 'money' },
      { key: 'inc_neg_col_ds280_24', label: 'Inc. DS280-24', type: 'money' },
      { key: 'inc_neg_col_ds326_25', label: 'Inc. DS326-25', type: 'money' },
      { key: 't_ingreso', label: 'Total Ingreso', type: 'money' },
      { key: 'base', label: 'Base', type: 'money' },
      { key: 'descuento_snp', label: 'Descuento S.N.P.', type: 'money' },
      { key: 'fdo_pens', label: 'Fdo. Pens.', type: 'money' },
      { key: 'p_seg', label: 'P. Seg.', type: 'money' },
      { key: 'c_var', label: 'C. Var.', type: 'money' },
      { key: 'ir_5ta_cat', label: 'IR 5ta Cat.', type: 'money' },
      { key: 'mas_vida', label: 'Más Vida', type: 'money' },
      { key: 'seg_rimac', label: 'Seg. Rimac', type: 'money' },
      { key: 'interseguro', label: 'Interseguro', type: 'money' },
      { key: 'd_aut_sit_mpi', label: 'D. Aut. SIT-MPI', type: 'money' },
      { key: 'dscto_otros', label: 'Dscto. Otros', type: 'money' },
      { key: 'coop_s_crist', label: 'Coop. S. Crist.', type: 'money' },
      { key: 'ccp', label: 'CCP', type: 'money' },
      { key: 'faltas_tarda', label: 'Faltas/Tardanzas', type: 'money' },
      { key: 'ret_jud', label: 'Ret. Jud.', type: 'money' },
      { key: 'dscto_aut_varios', label: 'Dscto. Aut. Varios', type: 'money' },
      { key: 'la_positiva_vida', label: 'La Positiva Vida', type: 'money' },
      { key: 'cep', label: 'CEP', type: 'money' },
      { key: 'c_sind_sit_mpi', label: 'C. Sind. SIT-MPI', type: 'money' },
      { key: 'clap', label: 'CLAP', type: 'money' },
      { key: 't_dsctos', label: 'Total Descuentos', type: 'money' },
      { key: 't_liquido', label: 'Total Líquido', type: 'money' },
      { key: 'firma', label: 'Firma', type: 'text' },
      { key: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
]

export function getPlanillaBySlug(slug) {
  return PLANILLAS.find((p) => p.slug === slug) ?? null
}

export function getPlanillaByTabla(tabla) {
  return PLANILLAS.find((p) => p.tabla === tabla) ?? null
}

export const GRUPOS = [...new Set(PLANILLAS.map((p) => p.grupo))]

/**
 * Clasifica las columnas money de una planilla en secciones de cálculo.
 * Retorna null si la planilla tiene sinAutoTotales=true o le faltan las columnas de total.
 *
 * Regla de posición:
 *   money ANTES de t_ingreso  → ingresos (se suman → t_ingreso)
 *   money ENTRE t_ingreso y t_dsctos → descuentos (se suman → t_dsctos)
 *   t_liquido = t_ingreso − t_dsctos
 */
export function getSeccionesCalculo(planilla) {
  if (planilla.sinAutoTotales) return null

  const cols = planilla.columnas
  const idxIngreso = cols.findIndex((c) => c.key === 't_ingreso')
  const idxDscto = cols.findIndex((c) => c.key === 't_dsctos')
  const idxLiquido = cols.findIndex((c) => c.key === 't_liquido')

  if (idxIngreso === -1 || idxDscto === -1 || idxLiquido === -1) return null

  const excluir = new Set(planilla.excluirCalculo ?? [])

  const ingresoKeys = cols
    .slice(0, idxIngreso)
    .filter((c) => c.type === 'money' && !excluir.has(c.key))
    .map((c) => c.key)

  const descuentoKeys = cols
    .slice(idxIngreso + 1, idxDscto)
    .filter((c) => c.type === 'money' && !excluir.has(c.key))
    .map((c) => c.key)

  return {
    ingresoKeys,
    descuentoKeys,
    totalIngreso: 't_ingreso',
    totalDscto: 't_dsctos',
    totalLiquido: 't_liquido',
  }
}
